# Etapa 2 - Primeiro Contato | Cancelamento de Clientes

## Leitura do arquivo | Tamanho do arquivo

In [62]:
# Bibliotecas
import pandas as pd  # Leitura e manipulação de arquivos
import os  # Informações do arquivo no disco

# Local do arquivo
caminho = "../data/raw/cancelamentos.csv"

# Leitura do arquivo
df_raw = pd.read_csv(
    caminho,
    sep=",",
    encoding="utf-8",
    decimal=".",
    low_memory=False,
)

## Inicio do dataframe

In [63]:
# Ínicio do dataframe
display(df_raw.head())

,CustomerID,idade,sexo,tempo_como_cliente,frequencia_uso,ligacoes_callcenter,dias_atraso,assinatura,duracao_contrato,total_gasto,meses_ultima_interacao,cancelou
0,349936.0,23.0,Male,13.0,22.0,2.0,1.0,Standard,Annual,909.58,23.0,0.0
1,100634.0,49.0,Male,55.0,16.0,3.0,6.0,Premium,Monthly,207.00,29.0,1.0
2,301263.0,30.0,Male,7.0,1.0,0.0,8.0,Basic,Annual,768.78,7.0,0.0
3,119358.0,26.0,Male,40.0,5.0,3.0,8.0,Premium,Annual,398.00,12.0,1.0
4,130955.0,27.0,Female,17.0,30.0,5.0,6.0,Basic,Annual,507.00,15.0,1.0

## Final do dataframe

In [64]:
# Final do dataframe
display(df_raw.tail())

,CustomerID,idade,sexo,tempo_como_cliente,frequencia_uso,ligacoes_callcenter,dias_atraso,assinatura,duracao_contrato,total_gasto,meses_ultima_interacao,cancelou
49995,195680.0,62.0,Female,35.0,7.0,2.0,8.0,Basic,Annual,232.00,15.0,1.0
49996,43477.0,36.0,Male,43.0,21.0,2.0,30.0,Basic,Quarterly,928.00,30.0,1.0
49997,169273.0,55.0,Male,42.0,8.0,1.0,12.0,Basic,Monthly,326.00,27.0,1.0
49998,310693.0,40.0,Female,14.0,19.0,1.0,17.0,Premium,Quarterly,826.76,12.0,0.0
49999,251915.0,64.0,Male,41.0,29.0,5.0,9.0,Basic,Quarterly,700.38,18.0,1.0

## Meio do dataframe

In [65]:
# Meio do dataframe
display(df_raw.sample(5, random_state=42))

,CustomerID,idade,sexo,tempo_como_cliente,frequencia_uso,ligacoes_callcenter,dias_atraso,assinatura,duracao_contrato,total_gasto,meses_ultima_interacao,cancelou
33553,6171.0,30.0,Male,52.0,10.0,2.0,4.0,Standard,Annual,322.00,4.0,1.0
9427,374447.0,49.0,Female,45.0,4.0,1.0,16.0,Basic,Quarterly,694.43,6.0,0.0
199,386050.0,32.0,Female,29.0,30.0,0.0,15.0,Premium,Annual,666.71,12.0,0.0
12447,14317.0,23.0,Female,7.0,20.0,2.0,24.0,Premium,Annual,407.00,3.0,1.0
39489,31945.0,56.0,Female,16.0,18.0,10.0,10.0,Premium,Quarterly,494.00,6.0,1.0

**Observação:**
* Início, meio e fim têm o mesmo formato e as mesmas 12 colunas.
* Valores inteiros aparacem com .0 (ex.: CustomerID = 349936.0, idade = 23.0).

## Tipo dos dados

In [66]:
# Tipo de dados e valores não nulos
df_raw.info()

# Tamanho do arquivo em disco
print(f"Tamanho do arquivo no disco: {os.path.getsize("../data/raw/cancelamentos.csv") / 1024**2:.2f} MB")

# Tamanho do arquivo na memória
print(f'Tamanho do dataframe na memória: {df_raw.memory_usage(deep=True).sum() / 1024**2:.2f} MB')

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              50000 non-null  float64
 1   idade                   50000 non-null  float64
 2   sexo                    49997 non-null  str
 3   tempo_como_cliente      49998 non-null  float64
 4   frequencia_uso          50000 non-null  float64
 5   ligacoes_callcenter     50000 non-null  float64
 6   dias_atraso             50000 non-null  float64
 7   assinatura              50000 non-null  str
 8   duracao_contrato        50000 non-null  str
 9   total_gasto             50000 non-null  float64
 10  meses_ultima_interacao  50000 non-null  float64
 11  cancelou                50000 non-null  float64
dtypes: float64(9), str(3)
memory usage: 4.6 MB
Tamanho do arquivo no disco: 3.34 MB
Tamanho do dataframe na memória: 11.35 MB

**Observação:**
* 50.000 linhas × 12 colunas.
* 3 coluna de texto (`str`): `sexo`, `assinatura` e `duração do contrato`.
* 9 colunas numéricas (`float64`): `CustomerID`, `idade`, `tempo_como_cliente`, `frequencia_uso`, `ligacoes_callcenter`, `dias_atraso`, `total_gasto`, `meses_ultima_interacao`, `cancelou`.
* Nulos: `sexo` (3) e `tempo_como_cliente` (2).
* Colunas que parecem inteiras: (CustomerID, idade, tempo_como_cliente, frequencia_uso, ligacoes_callcenter, dias_atraso, meses_ultima_interacao, cancelou).
* 3,34 MB em disco e 11,35 MB em memória (`deep=True`): a tabela carregada é maior que o arquivo, o que é esperado.

## Valores únicos e repetidos

In [71]:
# Identificador: o ID é único?
print(f"ID único: {df_raw['CustomerID'].nunique() == len(df_raw)}")

# IDs repetidos?
print(f"Quantidad de IDs repetidos: {df_raw['CustomerID'].duplicated().sum()}")

# Variável alvo: quais valores existem?
print(f"Valores da coluna alvo: {df_raw['cancelou'].unique()}")

ID único: False
Quantidad de IDs repetidos: 1469
Valores da coluna alvo: [0. 1.]

**Observação:**
* CustomerID **não é único:** 1.469 IDs repetidos -> granularidade "1 linha = 1 cliente" não confirmada (investigar na Etapa 3).
* Variável alvo `cancelou` existe, com valores `0.0` e `1.0`.