# Etapa 2 - Primeiro Contato | Cancelamento de Clientes

## Leitura do arquivo | Tamanho do arquivo

In [49]:
# Bibliotecas
import pandas as pd  # Leitura e manipulação dos arquivos
import os  # Manipulação de caminhos

# Local do arquivo (caminho relativo ao projeto)
caminho = "../data/raw/cancelamentos.csv"

# Tamanho do arquivo em disco (MB)
print(f"Tamanho do arquivo em disco: {os.path.getsize(caminho) / 1024 ** 2:.2f} MB")

# Leitura do arquivo (usando o Pandas)
df_raw = pd.read_csv(
    caminho,
    sep=",",
    encoding="utf-8",
    decimal=".",
    low_memory=False,
)

# Total de linha e colunas
print(f"Linhas: {df_raw.shape[0]}, Colunas: {df_raw.shape[1]}")

# Tamanho do dataframe na memória (MB)
print(
    f"Tamanho do dataframe na memória: {df_raw.memory_usage(deep=True).sum() / 1024 ** 2:.2f} MB"
)

Tamanho do arquivo em disco: 3.34 MB
Linhas: 50000, Colunas: 12
Tamanho do dataframe na memória: 11.35 MB

## Início do dataframe

In [50]:
# Início do dataframe
display(df_raw.head(6))

,CustomerID,idade,sexo,tempo_como_cliente,frequencia_uso,ligacoes_callcenter,dias_atraso,assinatura,duracao_contrato,total_gasto,meses_ultima_interacao,cancelou
0,349936.0,23.0,Male,13.0,22.0,2.0,1.0,Standard,Annual,909.58,23.0,0.0
1,100634.0,49.0,Male,55.0,16.0,3.0,6.0,Premium,Monthly,207.00,29.0,1.0
2,301263.0,30.0,Male,7.0,1.0,0.0,8.0,Basic,Annual,768.78,7.0,0.0
3,119358.0,26.0,Male,40.0,5.0,3.0,8.0,Premium,Annual,398.00,12.0,1.0
4,130955.0,27.0,Female,17.0,30.0,5.0,6.0,Basic,Annual,507.00,15.0,1.0
5,423992.0,30.0,NaN,NaN,12.0,3.0,7.0,Standard,Quarterly,641.78,7.0,0.0

## Final do dataframe

In [51]:
# Final do dataframe
display(df_raw.tail(6))

,CustomerID,idade,sexo,tempo_como_cliente,frequencia_uso,ligacoes_callcenter,dias_atraso,assinatura,duracao_contrato,total_gasto,meses_ultima_interacao,cancelou
49994,190074.0,63.0,Male,16.0,24.0,2.0,18.0,Standard,Quarterly,442.00,26.0,1.0
49995,195680.0,62.0,Female,35.0,7.0,2.0,8.0,Basic,Annual,232.00,15.0,1.0
49996,43477.0,36.0,Male,43.0,21.0,2.0,30.0,Basic,Quarterly,928.00,30.0,1.0
49997,169273.0,55.0,Male,42.0,8.0,1.0,12.0,Basic,Monthly,326.00,27.0,1.0
49998,310693.0,40.0,Female,14.0,19.0,1.0,17.0,Premium,Quarterly,826.76,12.0,0.0
49999,251915.0,64.0,Male,41.0,29.0,5.0,9.0,Basic,Quarterly,700.38,18.0,1.0

## Meio do dataframe

In [52]:
# Meio do dataframe (linha sorteadas)
display(df_raw.sample(6, random_state=42))

,CustomerID,idade,sexo,tempo_como_cliente,frequencia_uso,ligacoes_callcenter,dias_atraso,assinatura,duracao_contrato,total_gasto,meses_ultima_interacao,cancelou
33553,6171.0,30.0,Male,52.0,10.0,2.0,4.0,Standard,Annual,322.00,4.0,1.0
9427,374447.0,49.0,Female,45.0,4.0,1.0,16.0,Basic,Quarterly,694.43,6.0,0.0
199,386050.0,32.0,Female,29.0,30.0,0.0,15.0,Premium,Annual,666.71,12.0,0.0
12447,14317.0,23.0,Female,7.0,20.0,2.0,24.0,Premium,Annual,407.00,3.0,1.0
39489,31945.0,56.0,Female,16.0,18.0,10.0,10.0,Premium,Quarterly,494.00,6.0,1.0
42724,378703.0,37.0,Male,3.0,22.0,2.0,15.0,Standard,Annual,983.67,25.0,0.0

**Observação:**
* As 12 colunas são iguais do inicio ao fim.
* Existe valores nulos (NaN) nas colunas `sexo` e `tempo_como_cliente`.
* As colunas de texto são: `sexo`, `assinatura` e `duracao_contrato`.
* As colunas numéricas são **`(float64)`**:
    > `CustomerID`, `idade`, `tempo_como_cliente`, `frequencia_uso`, `ligacoes_callcenter`, `dias_atraso`, `total_gasto`, `meses_ultima_interacao` e `cancelou`.